## Calculating AQI (Air Quality Index) in India
![](https://i.imgur.com/GL2BaU4.png)

This notebook provides a workflow for calculating Air Quality Index. The formula is as per CPCB's official AQI Calculator: https://app.cpcbccr.com/ccr_docs/How_AQI_Calculated.pdf

## Preparing data
The dataset used is hourly air quality data (2015 - 2020) from various measuring stations across India: https://www.kaggle.com/rohanrao/air-quality-data-in-india

We'll use one city (Delhi) that has 38 stations and compare it with the actual AQI values present in the data at station, city, hour and day level to confirm the calculations are correct.

In [45]:
## importing packages
import numpy as np
import pandas as pd

In [46]:
## defining constants
PATH_STATION_HOUR = "C:/Users/mohit/Documents/Minor_Project/Temp_Other_Data/Kaggle_AQI/station_hour.csv"
PATH_STATION_DAY = "C:/Users/mohit/Documents/Minor_Project/Temp_Other_Data/Kaggle_AQI/station_day.csv"
PATH_CITY_HOUR = "C:/Users/mohit/Documents/Minor_Project/Temp_Other_Data/Kaggle_AQI/city_hour.csv"
PATH_CITY_DAY = "C:/Users/mohit/Documents/Minor_Project/Temp_Other_Data/Kaggle_AQI/city_day.csv"
PATH_STATIONS = "C:/Users/mohit/Documents/Minor_Project/Temp_Other_Data/Kaggle_AQI/stations.csv"

STATIONS = ["DL001", "DL002", "DL003", "DL004", "DL005", "DL006", "DL007", "DL008", "DL009", "DL010", "DL011", "DL012", "DL013", "DL014", "DL015", "DL016", "DL017", "DL018", 
           "DL019", "DL020", "DL021", "DL022", "DL023", "DL024", "DL025", "DL026", "DL027", "DL028", "DL029", "DL030", "DL031", "DL032", "DL033", "DL034", "DL035", "DL036", 
           "DL037", "DL038"]
# All Possible 38 Delhi Stations

In [49]:
## importing data and subsetting the station
df = pd.read_csv(PATH_STATION_HOUR, parse_dates = ["Datetime"])
stations = pd.read_csv(PATH_STATIONS)

df = df.merge(stations, on = "StationId")

df = df[df.StationId.isin(STATIONS)]
df.sort_values(["StationId", "Datetime"], inplace = True)
df["Date"] = df.Datetime.dt.date.astype(str)
df.Datetime = df.Datetime.astype(str)
df

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,...,Benzene,Toluene,Xylene,AQI,AQI_Bucket,StationName,City,State,Status,Date
141133,DL001,2018-11-11 15:00:00,130.00,274.00,1.70,54.00,30.10,NaN,0.80,26.40,...,3.40,15.30,0.10,NaN,NaN,"Alipur, Delhi - DPCC",Delhi,Delhi,Active,2018-11-11
141134,DL001,2018-11-11 16:00:00,133.25,279.00,1.70,55.07,30.67,25.55,0.83,27.97,...,3.68,15.08,0.10,NaN,NaN,"Alipur, Delhi - DPCC",Delhi,Delhi,Active,2018-11-11
141135,DL001,2018-11-11 17:00:00,140.25,284.25,1.58,55.88,30.97,24.30,0.85,24.80,...,3.33,12.27,0.10,NaN,NaN,"Alipur, Delhi - DPCC",Delhi,Delhi,Active,2018-11-11
141136,DL001,2018-11-11 18:00:00,153.25,332.00,1.63,64.05,35.40,28.57,1.53,20.25,...,3.85,13.33,0.15,NaN,NaN,"Alipur, Delhi - DPCC",Delhi,Delhi,Active,2018-11-11
141137,DL001,2018-11-11 19:00:00,247.00,575.00,1.75,80.07,43.98,37.90,1.68,18.00,...,6.80,19.02,0.30,NaN,NaN,"Alipur, Delhi - DPCC",Delhi,Delhi,Active,2018-11-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228516,DL038,2020-06-30 20:00:00,52.50,146.00,5.12,31.05,20.70,29.23,1.52,18.40,...,2.85,19.60,NaN,98.0,Satisfactory,"Wazirpur, Delhi - DPCC",Delhi,Delhi,Active,2020-06-30
1228517,DL038,2020-06-30 21:00:00,51.50,138.50,6.00,29.95,20.80,40.00,1.32,17.32,...,2.85,24.35,NaN,98.0,Satisfactory,"Wazirpur, Delhi - DPCC",Delhi,Delhi,Active,2020-06-30
1228518,DL038,2020-06-30 22:00:00,58.00,131.00,5.58,28.38,19.65,43.30,1.25,17.77,...,2.55,16.88,NaN,99.0,Satisfactory,"Wazirpur, Delhi - DPCC",Delhi,Delhi,Active,2020-06-30
1228519,DL038,2020-06-30 23:00:00,51.50,124.00,6.85,26.62,19.77,41.12,1.48,19.38,...,2.40,14.90,NaN,101.0,Moderate,"Wazirpur, Delhi - DPCC",Delhi,Delhi,Active,2020-06-30
1228520,DL038,2020-07-01 00:00:00,46.50,126.50,6.65,25.75,19.12,32.53,1.23,21.98,...,2.78,17.65,NaN,103.0,Moderate,"Wazirpur, Delhi - DPCC",Delhi,Delhi,Active,2020-07-01

## Formula
![](https://i.imgur.com/vQR5Zy0.png)

* The AQI calculation uses 7 measures: **PM2.5, PM10, SO2, NOx, NH3, CO and O3**.
* For **PM2.5, PM10, SO2, NOx and NH3** the average value in last 24-hrs is used with the condition of having at least 16 values.
* For **CO and O3** the maximum value in last 8-hrs is used.
* Each measure is converted into a Sub-Index based on pre-defined groups.
* Sometimes measures are not available due to lack of measuring or lack of required data points.
* Final AQI is the maximum Sub-Index with the condition that at least one of PM2.5 and PM10 should be available and at least three out of the seven should be available.

In [50]:
df["PM10_24hr_avg"] = df.groupby("StationId")["PM10"].rolling(window = 24, min_periods = 16).mean().values
df["PM2.5_24hr_avg"] = df.groupby("StationId")["PM2.5"].rolling(window = 24, min_periods = 16).mean().values
df["SO2_24hr_avg"] = df.groupby("StationId")["SO2"].rolling(window = 24, min_periods = 16).mean().values
df["NOx_24hr_avg"] = df.groupby("StationId")["NOx"].rolling(window = 24, min_periods = 16).mean().values
df["NH3_24hr_avg"] = df.groupby("StationId")["NH3"].rolling(window = 24, min_periods = 16).mean().values
df["CO_8hr_max"] = df.groupby("StationId")["CO"].rolling(window = 8, min_periods = 1).max().values
df["O3_8hr_max"] = df.groupby("StationId")["O3"].rolling(window = 8, min_periods = 1).max().values
df

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,...,State,Status,Date,PM10_24hr_avg,PM2.5_24hr_avg,SO2_24hr_avg,NOx_24hr_avg,NH3_24hr_avg,CO_8hr_max,O3_8hr_max
141133,DL001,2018-11-11 15:00:00,130.00,274.00,1.70,54.00,30.10,NaN,0.80,26.40,...,Delhi,Active,2018-11-11,NaN,NaN,NaN,NaN,NaN,0.80,NaN
141134,DL001,2018-11-11 16:00:00,133.25,279.00,1.70,55.07,30.67,25.55,0.83,27.97,...,Delhi,Active,2018-11-11,NaN,NaN,NaN,NaN,NaN,0.83,NaN
141135,DL001,2018-11-11 17:00:00,140.25,284.25,1.58,55.88,30.97,24.30,0.85,24.80,...,Delhi,Active,2018-11-11,NaN,NaN,NaN,NaN,NaN,0.85,105.23
141136,DL001,2018-11-11 18:00:00,153.25,332.00,1.63,64.05,35.40,28.57,1.53,20.25,...,Delhi,Active,2018-11-11,NaN,NaN,NaN,NaN,NaN,1.53,105.23
141137,DL001,2018-11-11 19:00:00,247.00,575.00,1.75,80.07,43.98,37.90,1.68,18.00,...,Delhi,Active,2018-11-11,NaN,NaN,NaN,NaN,NaN,1.68,105.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228516,DL038,2020-06-30 20:00:00,52.50,146.00,5.12,31.05,20.70,29.23,1.52,18.40,...,Delhi,Active,2020-06-30,95.652174,43.260870,18.993478,18.761304,28.411739,1.95,29.15
1228517,DL038,2020-06-30 21:00:00,51.50,138.50,6.00,29.95,20.80,40.00,1.32,17.32,...,Delhi,Active,2020-06-30,97.437500,43.604167,18.923750,18.846250,28.894583,1.95,29.15
1228518,DL038,2020-06-30 22:00:00,58.00,131.00,5.58,28.38,19.65,43.30,1.25,17.77,...,Delhi,Active,2020-06-30,99.333333,44.604167,18.851667,18.650417,29.071667,1.95,29.15
1228519,DL038,2020-06-30 23:00:00,51.50,124.00,6.85,26.62,19.77,41.12,1.48,19.38,...,Delhi,Active,2020-06-30,101.510417,45.489583,18.994583,18.567917,29.417083,1.77,29.15
1228520,DL038,2020-07-01 00:00:00,46.50,126.50,6.65,25.75,19.12,32.53,1.23,21.98,...,Delhi,Active,2020-07-01,104.697917,46.729167,19.261667,18.464583,29.691250,1.75,32.58

## PM2.5 (Particulate Matter 2.5-micrometer)
PM2.5 is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [33]:
## PM2.5 Sub-Index calculation
def get_PM25_subindex(x):
    if x <= 30:
        return x * 50 / 30
    elif x <= 60:
        return 50 + (x - 30) * 50 / 30
    elif x <= 90:
        return 100 + (x - 60) * 100 / 30
    elif x <= 120:
        return 200 + (x - 90) * 100 / 30
    elif x <= 250:
        return 300 + (x - 120) * 100 / 130
    elif x > 250:
        return 400 + (x - 250) * 100 / 130
    else:
        return 0

df["PM2.5_SubIndex"] = df["PM2.5_24hr_avg"].apply(lambda x: get_PM25_subindex(x))

## PM10 (Particulate Matter 10-micrometer)
PM10 is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [34]:
## PM10 Sub-Index calculation
def get_PM10_subindex(x):
    if x <= 50:
        return x
    elif x <= 100:
        return x
    elif x <= 250:
        return 100 + (x - 100) * 100 / 150
    elif x <= 350:
        return 200 + (x - 250)
    elif x <= 430:
        return 300 + (x - 350) * 100 / 80
    elif x > 430:
        return 400 + (x - 430) * 100 / 80
    else:
        return 0

df["PM10_SubIndex"] = df["PM10_24hr_avg"].apply(lambda x: get_PM10_subindex(x))

## SO2 (Sulphur Dioxide)
SO2 is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [35]:
## SO2 Sub-Index calculation
def get_SO2_subindex(x):
    if x <= 40:
        return x * 50 / 40
    elif x <= 80:
        return 50 + (x - 40) * 50 / 40
    elif x <= 380:
        return 100 + (x - 80) * 100 / 300
    elif x <= 800:
        return 200 + (x - 380) * 100 / 420
    elif x <= 1600:
        return 300 + (x - 800) * 100 / 800
    elif x > 1600:
        return 400 + (x - 1600) * 100 / 800
    else:
        return 0

df["SO2_SubIndex"] = df["SO2_24hr_avg"].apply(lambda x: get_SO2_subindex(x))

## NOx (Any Nitric x-oxide)
NOx is measured in ppb (parts per billion). The predefined groups are defined in the function below:

In [36]:
## NOx Sub-Index calculation
def get_NOx_subindex(x):
    if x <= 40:
        return x * 50 / 40
    elif x <= 80:
        return 50 + (x - 40) * 50 / 40
    elif x <= 180:
        return 100 + (x - 80) * 100 / 100
    elif x <= 280:
        return 200 + (x - 180) * 100 / 100
    elif x <= 400:
        return 300 + (x - 280) * 100 / 120
    elif x > 400:
        return 400 + (x - 400) * 100 / 120
    else:
        return 0

df["NOx_SubIndex"] = df["NOx_24hr_avg"].apply(lambda x: get_NOx_subindex(x))

## NH3 (Ammonia)
NH3 is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [37]:
## NH3 Sub-Index calculation
def get_NH3_subindex(x):
    if x <= 200:
        return x * 50 / 200
    elif x <= 400:
        return 50 + (x - 200) * 50 / 200
    elif x <= 800:
        return 100 + (x - 400) * 100 / 400
    elif x <= 1200:
        return 200 + (x - 800) * 100 / 400
    elif x <= 1800:
        return 300 + (x - 1200) * 100 / 600
    elif x > 1800:
        return 400 + (x - 1800) * 100 / 600
    else:
        return 0

df["NH3_SubIndex"] = df["NH3_24hr_avg"].apply(lambda x: get_NH3_subindex(x))

## CO (Carbon Monoxide)
CO is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [38]:
## CO Sub-Index calculation
def get_CO_subindex(x):
    if x <= 1:
        return x * 50 / 1
    elif x <= 2:
        return 50 + (x - 1) * 50 / 1
    elif x <= 10:
        return 100 + (x - 2) * 100 / 8
    elif x <= 17:
        return 200 + (x - 10) * 100 / 7
    elif x <= 34:
        return 300 + (x - 17) * 100 / 17
    elif x > 34:
        return 400 + (x - 34) * 100 / 17
    else:
        return 0

df["CO_SubIndex"] = df["CO_8hr_max"].apply(lambda x: get_CO_subindex(x))

## O3 (Ozone or Trioxygen)
O3 is measured in ug / m3 (micrograms per cubic meter of air). The predefined groups are defined in the function below:

In [39]:
## O3 Sub-Index calculation
def get_O3_subindex(x):
    if x <= 50:
        return x * 50 / 50
    elif x <= 100:
        return 50 + (x - 50) * 50 / 50
    elif x <= 168:
        return 100 + (x - 100) * 100 / 68
    elif x <= 208:
        return 200 + (x - 168) * 100 / 40
    elif x <= 748:
        return 300 + (x - 208) * 100 / 539
    elif x > 748:
        return 400 + (x - 400) * 100 / 539
    else:
        return 0

df["O3_SubIndex"] = df["O3_8hr_max"].apply(lambda x: get_O3_subindex(x))

## AQI
The final AQI is the maximum Sub-Index among the available sub-indices with the condition that at least one of PM2.5 and PM10 should be available and at least three out of the seven should be available.

There is no theoretical upper value of AQI but its rare to find values over 1000.

The pre-defined buckets of AQI are as follows:
![](https://i.imgur.com/XmnE0rT.png)

In [40]:
## AQI bucketing
def get_AQI_bucket(x):
    if x <= 50:
        return "Good"
    elif x <= 100:
        return "Satisfactory"
    elif x <= 200:
        return "Moderate"
    elif x <= 300:
        return "Poor"
    elif x <= 400:
        return "Very Poor"
    elif x > 400:
        return "Severe"
    else:
        return np.NaN

df["Checks"] = (df["PM2.5_SubIndex"] > 0).astype(int) + \
                (df["PM10_SubIndex"] > 0).astype(int) + \
                (df["SO2_SubIndex"] > 0).astype(int) + \
                (df["NOx_SubIndex"] > 0).astype(int) + \
                (df["NH3_SubIndex"] > 0).astype(int) + \
                (df["CO_SubIndex"] > 0).astype(int) + \
                (df["O3_SubIndex"] > 0).astype(int)

df["AQI_calculated"] = round(df[["PM2.5_SubIndex", "PM10_SubIndex", "SO2_SubIndex", "NOx_SubIndex",
                                 "NH3_SubIndex", "CO_SubIndex", "O3_SubIndex"]].max(axis = 1))
df.loc[df["PM2.5_SubIndex"] + df["PM10_SubIndex"] <= 0, "AQI_calculated"] = np.NaN
df.loc[df.Checks < 3, "AQI_calculated"] = np.NaN

df["AQI_bucket_calculated"] = df["AQI_calculated"].apply(lambda x: get_AQI_bucket(x))
df[~df.AQI_calculated.isna()].head(100)

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,...,PM2.5_SubIndex,PM10_SubIndex,SO2_SubIndex,NOx_SubIndex,NH3_SubIndex,CO_SubIndex,O3_SubIndex,Checks,AQI_calculated,AQI_bucket_calculated
141148,DL001,2018-11-12 06:00:00,263.00,321.75,3.17,50.93,29.62,32.42,1.55,NaN,...,408.365385,368.417969,0.000000,50.691406,0.000000,100.0,14.68,5,408.0,Severe
141149,DL001,2018-11-12 07:00:00,247.25,301.50,6.00,74.40,44.52,37.63,1.60,NaN,...,407.748869,360.827206,0.000000,50.983088,9.070937,90.0,6.93,6,408.0,Severe
141150,DL001,2018-11-12 08:00:00,230.25,294.00,6.83,73.97,44.93,40.15,1.63,NaN,...,406.474359,353.559028,0.000000,51.270833,9.127794,87.5,4.77,6,406.0,Severe
141151,DL001,2018-11-12 09:00:00,245.50,334.00,8.05,97.02,58.15,42.28,1.75,NaN,...,405.951417,349.687500,0.000000,52.398026,9.207917,87.5,13.50,6,406.0,Severe
141152,DL001,2018-11-12 10:00:00,262.00,400.00,3.62,93.30,52.60,43.82,1.70,NaN,...,406.115385,350.328125,0.000000,53.065625,9.299868,87.5,44.95,6,406.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141243,DL001,2018-11-16 05:00:00,174.50,227.00,2.40,74.90,41.77,31.25,0.90,7.77,...,315.016026,160.590278,15.875000,53.579687,7.849688,70.0,21.23,7,315.0,Very Poor
141244,DL001,2018-11-16 06:00:00,172.75,238.25,1.70,48.65,27.28,23.05,0.48,9.23,...,317.419872,163.583333,16.006771,52.634896,7.727813,70.0,22.93,7,317.0,Very Poor
141245,DL001,2018-11-16 07:00:00,147.50,203.50,1.97,47.15,26.68,22.58,0.70,8.97,...,319.270833,165.937500,16.031250,52.261458,7.688021,70.0,22.93,7,319.0,Very Poor
141246,DL001,2018-11-16 08:00:00,154.50,218.50,3.73,48.85,29.02,22.15,0.63,8.62,...,321.482372,169.062500,15.954167,52.391667,7.694063,70.0,22.93,7,321.0,Very Poor
141247,DL001,2018-11-16 09:00:00,151.50,207.00,3.52,42.88,25.65,22.50,0.58,12.30,...,323.605769,171.854167,16.060938,52.239583,7.712813,57.5,37.08,7,324.0,Very Poor

In [41]:
df[~df.AQI_calculated.isna()].AQI_bucket_calculated.value_counts()

Moderate        271309
Very Poor       213168
Poor            150475
Satisfactory    112860
Severe           88040
Good             10248
Name: AQI_bucket_calculated, dtype: int64

## Day level
To get AQI at day level, the AQI values are averaged over the hours of the day.

In [42]:
df_station_hour = df
df_station_day = pd.read_csv(PATH_STATION_DAY)

df_station_day = df_station_day.merge(df.groupby(["StationId", "Date"])["AQI_calculated"].mean().reset_index(), on = ["StationId", "Date"])
df_station_day.AQI_calculated = round(df_station_day.AQI_calculated)

## City level
To get AQI at city level, the AQI values are averaged over stations of the city.

In [43]:
df_city_hour = pd.read_csv(PATH_CITY_HOUR)
df_city_day = pd.read_csv(PATH_CITY_DAY)

df_city_hour["Date"] = pd.to_datetime(df_city_hour.Datetime).dt.date.astype(str)

df_city_hour = df_city_hour.merge(df.groupby(["City", "Datetime"])["AQI_calculated"].mean().reset_index(), on = ["City", "Datetime"])
df_city_hour.AQI_calculated = round(df_city_hour.AQI_calculated)

df_city_day = df_city_day.merge(df_city_hour.groupby(["City", "Date"])["AQI_calculated"].mean().reset_index(), on = ["City", "Date"])
df_city_day.AQI_calculated = round(df_city_day.AQI_calculated)

## Verification
Since this exact formula is used for AQI calculated, lets quickly compare it with the actual AQI values present in the raw data at each of the four levels.

In [44]:
df_check_station_hour = df_station_hour[["AQI", "AQI_calculated"]].dropna()
df_check_station_day = df_station_day[["AQI", "AQI_calculated"]].dropna()
df_check_city_hour = df_city_hour[["AQI", "AQI_calculated"]].dropna()
df_check_city_day = df_city_day[["AQI", "AQI_calculated"]].dropna()

print("Station + Hour")
print("Rows: ", df_check_station_hour.shape[0])
print("Matched AQI: ", (df_check_station_hour.AQI == df_check_station_hour.AQI_calculated).sum())
print("% Match: ", (df_check_station_hour.AQI == df_check_station_hour.AQI_calculated).sum() * 100 / df_check_station_hour.shape[0])
print("\n")
print("Station + Day")
print("Rows: ", df_check_station_day.shape[0])
print("Matched AQI: ", (df_check_station_day.AQI == df_check_station_day.AQI_calculated).sum())
print("% Match: ", (df_check_station_day.AQI == df_check_station_day.AQI_calculated).sum() * 100 / df_check_station_day.shape[0])
print("\n")
print("City + Hour")
print("Rows: ", df_check_city_hour.shape[0])
print("Matched AQI: ", (df_check_city_hour.AQI == df_check_city_hour.AQI_calculated).sum())
print("% Match: ", (df_check_city_hour.AQI == df_check_city_hour.AQI_calculated).sum() * 100 / df_check_city_hour.shape[0])
print("\n")
print("City + Day")
print("Rows: ", df_check_city_day.shape[0])
print("Matched AQI: ", (df_check_city_day.AQI == df_check_city_day.AQI_calculated).sum())
print("% Match: ", (df_check_city_day.AQI == df_check_city_day.AQI_calculated).sum() * 100 / df_check_city_day.shape[0])

Station + Hour
Rows:  846100
Matched AQI:  846100
% Match:  100.0


Station + Day
Rows:  36107
Matched AQI:  36107
% Match:  100.0


City + Hour
Rows:  47694
Matched AQI:  47694
% Match:  100.0


City + Day
Rows:  1999
Matched AQI:  1999
% Match:  100.0